# Generated by Django 2.2.24 on 2021-12-17 20:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 19, 20, 21, 3, 392101, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
