# Generated by Django 2.2.24 on 2021-11-30 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0002_auto_20211122_1755'),
        ('authnapp', '0002_user_model_extend'),
    ]

    operations = [
    ]
